### ISSUE TITLE
Animated SVG's show up completely black in IE11

### ISSUE THREAD

**Issue by crystalrubik** [cdig/cd-module#10]
Animated SVG caution sign is completely black in IE11.

![img_4203](https://cloud.githubusercontent.com/assets/8481323/6255463/547ce6b0-b76d-11e4-989e-f370394bbc47.JPG)

IE11, Windows 7
Trican Acid Project, Das Scada & Sensors Module

**Comment by ivyreese** [comment]
That's probably because the CSS isn't reaching the right place in the SVG tree. You might need to play with the selectors and see what it takes to get it to work. We've definitely made this kind of thing work before, so I'd be very surprised if it wouldn't be reasonably simple to solve.

**Comment by theseanzo** [comment]
So, CSS can't animate SVGs in Internet Explorer unfortunately. What I've done is make a small coffeescript file for this and sent it to Crystal. It's temporary as I'm going to try and build a more long term solution for having SVG animations done with Javascript.
