### ISSUE TITLE
All underlines in IE11 are red

### ISSUE THREAD

**Issue by crystalrubik** [cdig/cd-module#11]
All the titles with underlines in IE11 are red, not orange to match the title. 

IE11, Windows 7
Trican Acid Project, Das Scada & Sensors Module

**Comment by ivyreese** [comment]
Can you attach a screenshot?

**Comment by crystalrubik** [comment]
Well, they appear to be orange now.... I swear, they were red. Lol. Nathan is a witness!

**Comment by ivyreese** [comment]
I've only ever seen orange.

I suspect it's an issue with specificity. This should be easily testable by introducing some hacks to see what it would take to override the "underline" colour. Note, the underline is actually a background gradient added by the [magic-underlines](https://github.com/cdig/cd-module#magic-underlines) mixin.

**Comment by theseanzo** [comment]
It seems that the rules for currentColor in IE are different than those in Chrome, Firefox, and Safari. I'm trying to resolve this right now.

**Comment by ivyreese** [comment]
Fascinating — is it case-sensitivity? I've seen examples of "currentcolor" and "currentColor".

Whatever it is, when you find out for sure, please add a note to [Why Can't I Use?](https://github.com/cdig/why-cant-i-use) about it. I want that to be the in-house document for all that we learn about cross-platform weirdness.
