### ISSUE TITLE
Need method to hide HTML content associated with cd-swf if it fails to load

### ISSUE THREAD

**Issue by theseanzo** [cdig/cd-module#12]
current problem is that if Flash is not installed, all of the HTML content associated with that flash object still loads.

**Comment by ivyreese** [comment]
I'm totally cool with introducing a rapper element. Thanks Siri.

**Comment by ivyreese** [comment]
Why not just set the fallback content to have a very high z-index, like 1000? We could bump the other low 1000s up a point to make room. See here: https://github.com/cdig/cd-module

**Comment by ivyreese** [comment]
This is going to be "fixed" in v2 by deprecating SWF content. In other words, it's being...

CLOSED AS WONTFIX :cake: :fire: :boom:
