### ISSUE TITLE
Cannot put a cd-swf inside of a div, inside of a cd-row in Firefox, in column view

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/cd-module#14]
Problem rating - concerning, but not urgent. Workaround in use.

I needed to a cd-swf and a cd-activity inside of a cd-row, so I grouped them into a div. This works great until I check it in column view, in Firefox developer. Then, the .swf disappears. Removing the activity makes no difference, but if I pull the div out, the swf is fine. (it makes 3 columns instead of the two I want, to allow for the cd-activity.)

I've done a lot of fiddling, and the cd-activity is not the problem. It seems that any combination of things that involve a cd-swf inside of a div will cause this problem. Remove the div, and the swf is happy again. 

I've found a workaround for my particular case by putting the cd-activity above the cd-row, which removes the need for the div around the swf. But if I had wanted to group some text, or an image with that swf, I would be out of luck. This only seems to be a problem in Firefox, column view. It is handled nicely everywhere else. If you would like to see the exact example I'm working on, it's in Basic Hydrostatic Loops (circuit), and the page is What is a Closed Loop?

**Comment by iMcKelvie** [comment]
More examples have been found in that same module; in the What Difference Does It Make section. I'll redesign as needed to remove the divs.

**Comment by ivyreese** [comment]
This is being fixed in v2 by removing column-orientation from cd-row.
