### ISSUE TITLE
Getting "Your Browser is Outdated" warning when testing in Chrome

### ISSUE THREAD

**Issue by Nathanoid** [cdig/cd-module#19]
I am not 100% certain that this actually is a bug and not just something I've overlooked but I am getting the "Your Browser is Outdated" warning when testing a module in Chrome.

**Comment by ivyreese** [comment]
That means the JS is failing to load. Try running a bower update, refreshing codekit, and recompiling.

**Comment by theseanzo** [comment]
Libs.js issue. Resolved.
