### ISSUE TITLE
Audio service issues in Internet Explorer 11

### ISSUE THREAD

**Issue by theseanzo** [cdig/cd-module#20]
Only the initial audio track will play in Internet Explorer 11

Tested in ball injector inside of components

**Comment by iMcKelvie** [comment]
Sean - what are the odds? I think you picked one of the two modules that may not be ready for audio yet. I had some changes to make to that module and I don't think I've updated the audio files to match the new IDs (waiting on approval from the Trican guys on those changes before we re-record.) This may not be a problem! Pick any module to test, other than Ball Injector or Bowie Pump Maintenance, and it should be in working order. Sorry about that!

**Comment by theseanzo** [comment]
This works! My bad.
