### ISSUE TITLE
When awarding points, calls to SCORM slow down module

### ISSUE THREAD

**Issue by theseanzo** [cdig/cd-module#23]

**Comment by ivyreese** [comment]
Just to be pedantic, it's likely all calls to SCORM being slow. I'm pretty sure it's a per-call latency, and nothing to do with the payload size.

We talked about this one, right? Should be a 1-change fix? (Remove the debug save-on-award)

**Comment by theseanzo** [comment]
Also, @ivanreese, it turned out to be 2 lines but I got stuck trying to figure out why the "reset" functionality broke after. I documented my fix for it, but ended up hacking through code being confused as to why the problem kept happening. Such is life!
