### ISSUE TITLE
Grey spaces in module are too large

### ISSUE THREAD

**Issue by theseanzo** [cdig/cd-module#24]
@ivanreese what do you think about this? Should we resolve it? It's not a hard fix.

**Comment by ivyreese** [comment]
Grey spaces?

**Comment by ivyreese** [comment]
Ah — spaces between pages, yes?

Closing as "not a big deal" and "a matter of taste" and "should use vh so that they look good on all screens" and "hey, I'm stoked about the new Star Wars"
