### ISSUE TITLE
Video still an issue on iPhone and iPad

### ISSUE THREAD

**Issue by crystalrubik** [cdig/cd-module#27]
I left one repeating video on a Pressure and Flow module we just uploaded to LBS. I know I've mentioned before that the labels show on a blank background with a play button on the iPhone at first. Then when you press play it opens up in a screen to play the video (without labels) and once that's done, it will show a preview now, with or without all the labels, plus the play button.

Another issue I just found is the iPad Mini doesn't even show a play button, so you can't see a video, no matter how much I click. (see attached image). So I'm going to go ahead and place an image there instead for now. 
![ipadmini](https://cloud.githubusercontent.com/assets/8481323/7863556/49cd7ff4-051a-11e5-8b85-1d9881b8ce35.jpg)

You can still check it out on LBS in the "In Development > Crystal > Pressure and Flow" on the "Positive Displacement Pump" page.

**Comment by ivyreese** [comment]
Unfortunately, we don't get to have auto-playing video on iOS. The video playback must be initiated by the user:

> In Safari on iOS (for all devices, including iPad), where the user may be on a cellular network and be charged per data unit, preload and autoplay are disabled. No data is loaded until the user initiates it. This means the JavaScript play() and load() methods are also inactive until the user initiates playback, unless the play() or load() method is triggered by user action. In other words, a user-initiated Play button works, but an onLoad="play()" event does not.
> - Apple
> https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html#//apple_ref/doc/uid/TP40009523-CH5-SW1

There are some alternatives to HTML5 video, but they all have downsides.
- We could use GIFs, but they are very bad for data compression: http://blog.embed.ly/post/89265229166/what-twitter-isnt-telling-you-about-gifs
- We could use animated PNGs, but they are only supported in Firefox and Safari: http://caniuse.com/#feat=apng
- We could use a custom JS canvas diff-painting solution, but those are freaking crazy: http://stackoverflow.com/questions/18742153/how-does-apple-compresses-video-using-jpeg-json-and-canvas

Currently, I recommend that we avoid designing around auto-playing video, or using video as a background element. We can get this eventually, but we need to make sure we do it in a way that satisfies all our constraints (load time performance, runtime performance, developer efficiency, quality, etc)

**Comment by crystalrubik** [comment]
I figured that's why Apple devices didn't allow autoplay, makes sense. Too bad for us though! 

Another issue was looping videos stopped for a brief second at every loop, so the video solution wasn't that nice anyway. It seemed to happen in the conversion to .mp4 from .mov.

**Comment by ivyreese** [comment]
Doing seamless loops is going to be a bit tricky, yes.

Our needs are unique enough that our solution will probably be unique (that is, custom in-house code) too.

**Comment by crystalrubik** [comment]
Sounds about right! We all look forward to that. :)
