### ISSUE TITLE
Color Key Button component isn't clickable on iPhone 5S

### ISSUE THREAD

**Issue by crystalrubik** [cdig/cd-module#31]
I tested out Ivan's nifty color key button code everything we have here and it works on all these devices:
iPhone 6
iMac Safari, Chrome & FF
Windows 7 IE, Chrome & FF
iPad Mini

Doesn't work on:
iPhone 5S

Nothing pops up, as if it isn't a button. This was tested through CodeKit. Not on LBS yet.

**Comment by ivyreese** [comment]
Fixed
