### ISSUE TITLE
points animation appears behind swfs

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/cd-module#5]
In IE and Firefox on the PC, the points animations occur behind their swfs, so you don't know anything is happening, unless the swf is shorter than the window. Non-swf activities are ok, though. (for example, the  points from mousing over a callout appear properly.) Chrome (PC) is fine.

**Comment by iMcKelvie** [comment]
Same result with two different modules. Last bower update was moments ago, just to make sure.

**Comment by ivyreese** [comment]
This is a known issue. In order to make SWFs run fast on old machines, they have to be embedded in such a way that they render on top of all other elements, completely ignoring z-index.

So, we have to make a tradeoff — slower SWFs, or stupid depth-sorting?

**Comment by ivyreese** [comment]
I opted to sacrifice performance. We're striving to remove SWFs from modules anyways, so if they perform badly, it'll give us even more cause to get rid of them.
