### ISSUE TITLE
Can't share our work on the local network

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/cd-module#52]
We used to be able to share a link to the module that codekit was running with any computer on the local network. It seems we can't do that anymore.

**Comment by ivyreese** [comment]
When you fire up gulp, you should see it print out 2 URLs.

Local: localhost:3000
External: some IP address

Try the external address.

**Comment by ivyreese** [comment]
Let me know if that works / doesn't work.

**Comment by iMcKelvie** [comment]
yes, that works thank you!
