### ISSUE TITLE
Comments form at the end of each module

### ISSUE THREAD

**Issue by AlexCDIG** [cdig/cd-module#60]
It will be useful and will create flow for proper reporting mistakes and suggestion from students on module context. It can be similar format what we using in end of quiz on quizzer.

**Comment by ivyreese** [comment]
Excellent suggestion! Thanks Alex.

We'll have the infrastructure in place to support something like this by v4, slated for spring/summer. I know that seems like an awfully long wait for such a simple feature, but as it stands right now, we don't have a good way to safely/securely transmit and store data generated by users of our modules — that technology has to be built first. Then, we can add a bunch of cool features like this one.

**Comment by ivyreese** [comment]
This idea is in the bucket! https://github.com/cdig/lunchboxsessions/wiki/Idea-Bucket#feedback-box
