### ISSUE TITLE
WelcomePopup layout is weird in IE

### ISSUE THREAD

**Issue by ivyreese** [cdig/cd-module#7]
In IE10 (possibly 11 too), the "Okay" button doesn't sit in the correct position. It's pretty gross.

**Comment by crystalrubik** [comment]
The underline is orange on the welcome popup in IE 11. The "Okay" button appears to be fine. 

![ie 11](https://cloud.githubusercontent.com/assets/8481323/6423088/058cef0e-be9e-11e4-8a4f-7a517e93b759.png)

**Comment by theseanzo** [comment]
The underline issue is resolved now.

**Comment by ivyreese** [comment]
Any particular commit? I'd love to see what the bug/fix was.

**Comment by theseanzo** [comment]
https://github.com/cdig/cd-module/commit/c5bbc0cfe58e334325febd7ca5c6b9f61ec977f0

**Comment by ivyreese** [comment]
Thanks!
