### ISSUE TITLE
Text has no padding in IE11 in small screen sizes

### ISSUE THREAD

**Issue by crystalrubik** [cdig/cd-module#8]
Any text inside a cd-row wrapped in only a paragraph tag has no padding at screen sizes below iPhoneLandscape.

IE11, Windows 7
Trican Acid Project, Das Scada & Sensors Module

**Comment by crystalrubik** [comment]
Wrap paragraph tags in a div.

**Comment by ivyreese** [comment]
I'm going to reopen this, just because it is a bug that should be investigated and fixed, if possible. Thanks for posting the workaround, though. That's helpful.

**Comment by ivyreese** [comment]
This is going to be fixed in v2, as part of removing smartphone support and revisiting all the layout primitives.
